### ISSUE TITLE
Special characters do not work

### ISSUE THREAD

**Issue by eazuviria** [vtex-apps/salesforce-chat#1]
when I complete the url fields, for example, the special characters are changed to urls encoding and the script does not work

![image](https://user-images.githubusercontent.com/45159054/71518312-fb9d1980-2890-11ea-8033-7c05e58ef8e8.png)
![image](https://user-images.githubusercontent.com/45159054/71518322-0a83cc00-2891-11ea-9451-e9b9aced9d91.png)

**Comment by ccamargo2294** [comment]
Fixed https://github.com/vtex-apps/salesforce-chat/pull/2 in version 0.0.2
